# Generated by Django 5.2.8 on 2025-12-15 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome da Categoria')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome comercial do produto', max_length=100, verbose_name='Nome do Produto')),
                ('marca', models.CharField(help_text='Fabricante ou marca do produto', max_length=50, verbose_name='Marca')),
                ('preco', models.DecimalField(decimal_places=2, help_text='Preço unitário do produto', max_digits=10, verbose_name='Preço')),
                ('descricao', models.TextField(help_text='Detalhes técnicos ou descrição comercial', null=True, verbose_name='Descrição')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/')),
                ('ativo', models.BooleanField(default=True)),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('atualizado', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='produtos.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'db_table': 'produtos',
                'ordering': ['nome'],
            },
        ),
    ]
