"""
Django settings for docelar project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta

# 10 pontos - upload de imagens
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 10 pontos - upload de imagens
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6b%-n^-r6fc&7p6(1nvw_1qjs$gfmal6bn+l$bf3z$h^6pw#+$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

	'rest_framework',
    'rest_framework_simplejwt',
    # você está dizendo ao Django que irá usar a biblioteca SimpleJWT, responsável por gerar e validar tokens JWT.
    'corsheaders',

	'usuarios',
    'produtos',
]
REST_FRAMEWORK = {
	'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination', 
	'PAGE_SIZE': 10,
    # Define o tipo de autenticação padrão da sua API
    # A API agora entende JWT como autenticação principal.
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # 'rest_framework_simplejwt.authentication.JWTAuthentication',
        # usar a autenticação olhando nosso banco
        'usuarios.authentication.CustomJWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    # Define a permissão padrão para toda API
    # GET está liberado para todos
    # POST, PUT, DELETE só funcionam com usuário autenticado
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ),
}
# 5 pontos - logout via API (mudar BlacklistAfterRotation para True)
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=5),  # Token válido por 5 horas, é o token principal usado nas requisições
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),  # Refresh válido por 1 dia, serve para pedir novos access tokens sem precisar logar de novo
    'ROTATE_REFRESH_TOKENS': False, # se fosse True, cada vez que o usuário pedisse um novo token, ele receberia novo refresh.
    'BLACKLIST_AFTER_ROTATION': True, # define se o refresh token antigo deve ser invalidado quando um novo token é emitido.
    # sobre rotate refresh token -> True = maior segurança, False = menor segurança
    # quando é True, cada vez que o usuário pedisse um novo token, ele receberia novo refresh.
    # ai a ideia é que o refresh token antigo seja invalidado quando um novo token é emitido.
    # por isso deve ativar o blacklist_after_rotation = True
    'UPDATE_LAST_LOGIN': False,

    'ALGORITHM': 'HS256',  # Algoritmo usado para assinar o token
    'SIGNING_KEY': SECRET_KEY,  # Chave usada para assinar o token
    'VERIFYING_KEY': None,  # É a chave pública usada para verificar tokens quando você usa algoritmos assimétricos (como RS256).
    'AUDIENCE': None, # É um campo opcional dentro do JWT que diz para qual público o token é destinado.
    'ISSUER': None, # Define quem emitiu o token

    'AUTH_HEADER_TYPES': ('Bearer',), # Define o cabeçalho usado para autenticação
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION', 
    'USER_ID_FIELD': 'id', # Define o campo usado para identificar o usuário
    'USER_ID_CLAIM': 'user_id', # e qual chave aparece dentro do JWT (user_id)

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',), # Define o token usado para autenticação
    'TOKEN_TYPE_CLAIM': 'token_type', 
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware', # <--- ADICIONE ESTA LINHA AQUI
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ============================================
# CONFIGURAÇÕES DE CORS
# ============================================

# DESENVOLVIMENTO: Permitir todas as origens
CORS_ALLOW_ALL_ORIGINS = True

# OU especificar origens permitidas (PRODUÇÃO):
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:5500",
#     "http://127.0.0.1:5500",
#     "https://meusite.com",
# ]

# Permitir credenciais (cookies, auth headers)
CORS_ALLOW_CREDENTIALS = True

# Headers permitidos
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

ROOT_URLCONF = 'docelar.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'docelar.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
